tasks:
  - init: pip install -r requirements && pip install tensorflow && pip install tree_sitter_parsers
    command: if [ ! -f unique.tar.xz ]; then wget https://github.com/yijunyu/cargo-geiger/raw/datasets/datasets/unique.tar.xz && mkdir data && tar xvfj unique.tar.xz -C data fi && cd inference && source process_data.sh && source inference.sh
